name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Compile WASM
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: wasm-pack build -t web

    - name: Upload pkg directory
      uses: actions/upload-artifact@v2
      with:
        name: pkg
        path: pkg/

  build-ui:
    needs: build-wasm
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download pkg artifact
      uses: actions/download-artifact@v2
      with:
        name: pkg
        path: ui/src/lib/moska

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install
      working-directory: ui

    - name: Run build
      run: npm run build
      working-directory: ui

    - name: Upload dist directory
      uses: actions/upload-artifact@v2
      with:
        name: github-pages
        path: ui/dist/

  publish:
    needs: build-ui
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
       # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source

      # Deploy to the github-pages environment
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      # Specify runner + deployment step
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
