name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Compile WASM
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: wasm-pack build -t web

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version you need

    - name: Upload pkg directory
      uses: actions/upload-artifact@v2
      with:
        name: pkg
        path: pkg/

  build-ui:
    needs: build-wasm
    runs-on: ubuntu-latest
    working-directory: ui

    steps:
    - name: Download pkg artifact
      uses: actions/download-artifact@v2
      with:
        name: pgk
        path: ui/dist/moska

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Upload dist directory
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  publish:
    needs: build-ui
    runs-on: ubuntu-latest

    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: /pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /pages/
